spring:
  profiles:
    active: dev
  liquibase:
    enabled: false
server:
  servlet:
    context-path: /voting
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: src/main/resources/cert/certificate.p12
#    key-store-password: slpolitics
#    key-store-type: PKCS12
#    key-alias: slpolitics

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_VOTING_HOST:localhost}:3306/slnews-voting
    username: ${DB_VOTING_USER:voting-user}
    password: ${DB_VOTING_PASS:password}
    hikari:
      max-lifetime: 360000 # 1 hour
  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
#    generate-ddl: true
    hibernate:
#      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  file:
    path: logs
---
spring:
  config:
    activate:
      on-profile: test
